// src/data/techStackData.js
import {
  FaReact,
  FaPython,
  FaJava,
  FaNodeJs,
  FaAngular,
  FaVuejs,
  FaDocker,
  FaAws,
  FaGitAlt,
} from "react-icons/fa";
import {
  SiTypescript,
  SiSpringboot,
  SiDjango,
  SiKubernetes,
  SiRust,
  SiJavascript,
} from "react-icons/si";

const fullTechData = [
  {
    icon: FaReact ,
    name: "React.js",
    color: "text-[#61DBFB] ",
    type1: "Basic",
    type2: "Medium",
    type3: "Advanced",
    info: "Component-based frontend framework for dynamic UIs.",
    href: "/React",
  },
  {
    icon: FaNodeJs  ,
    name: "Node.js",
    color: " text-[#3C873A]",
    type1: "Basic",
    type2: "Medium",
    type3: "Advanced",
    info: "JavaScript runtime for scalable server-side apps.",
    href: "/Node",
  },
  {
    icon: FaPython  ,
    name: "Python",
    color: " text-[#3776AB]",
    type1: "Basic",
    type2: "Medium",
    type3: "Advanced",
    info: "Versatile scripting language for web, data, and automation.",
    href: "/Python",
  },
  {
    icon: FaJava  ,
    name: "Java",
    color: " text-[#007396]",
    type1: "Basic",
    type2: "Medium",
    type3: "Advanced",
    info: "Robust OOP language for backend, Android, and enterprise apps.",
    href: "/Java",
  },
  {
    icon: SiSpringboot  ,
    name: "Spring Boot",
    color: " text-green-600",
    type1: "Basic",
    type2: "Medium",
    type3: "Advanced",
    info: "Powerful Java backend framework for microservices.",
    href: "/SpringBoot",
  },
  {
    icon: SiDjango  ,
    name: "Django",
    color: "text-[#092E20]",
    type1: "Basic",
    type2: "Medium",
    type3: "Advanced",
    info: "Python web framework for clean, pragmatic apps.",
    href: "/Django",
  },
  {
    icon: FaAngular ,
    name: "Angular",
    color: "text-red-600 ",
    type1: "Basic",
    type2: "Medium",
    type3: "Advanced",
    info: "Full-featured frontend framework by Google.",
    href: "/Angular",
  },
  {
    icon: FaVuejs  ,
    name: "Vue.js",
    color: " text-green-500",
    type1: "Basic",
    type2: "Medium",
    type3: "Advanced",
    info: "Progressive JavaScript framework for UI building.",
    href: "/Vue",
  },
  {
    icon: SiTypescript  ,
    name: "TypeScript",
    color: " text-[#3178C6]",
    type1: "Basic",
    type2: "Medium",
    type3: "Advanced",
    info: "Typed superset of JavaScript for scalable apps.",
    href: "/TypeScript",
  },
  {
  icon: SiJavascript,
  name: "JavaScript",
  color: "text-yellow-400",
  type1: "Basic",
  type2: "Medium",
  type3: "Advanced",
  info: "Versatile scripting language for frontend and backend development.",
  href: "/JavaScript",
},
  {
    icon: SiRust ,
    name: "Rust",
    color: " text-orange-70",
    type1: "Basic",
    type2: "Medium",
    type3: "Advanced",
    info: "Systems programming language known for safety and speed.",
    href: "/Rust",
  },
  {
    icon: FaDocker  ,
    name: "Docker",
    color: " text-[#2496ED]",
    type1: "Basic",
    type2: "Medium",
    type3: "Advanced",
    info: "Container platform to build, ship, and run applications.",
    href: "/Docker",
  },
  {
    icon: SiKubernetes  ,
    name: "Kubernetes",
    color: " text-[#326CE5]",
    type1: "Basic",
    type2: "Medium",
    type3: "Advanced",
    info: "Orchestration for deploying containerized apps.",
    href: "/Kubernetes",
  },
  {
    icon: FaAws ,
    name: "AWS",
    color: "text-[#FF9900]  ",
    type1: "Basic",
    type2: "Medium",
    type3: "Advanced",
    info: "Cloud platform offering compute, storage, and databases.",
    href: "/AWS",
  },
  {
    icon: FaGitAlt ,
    color: "  text-[#F1502F]",
    name: "Git",
    type1: "Basic",
    type2: "Medium",
    type3: "Advanced",
    info: "Version control system for code collaboration.",
    href: "/Git",
  },
];

export default fullTechData;
